package com.bloggingit.odata.olingo.annotation.edm;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for a EDM/CSDL EntitySet element.
 * <p>
 * EdmEntitySet is the container for entity type instances as described in the
 * OData protocol. The {@link EdmEntitySet} annotation defines the annotated
 * class as entity set and must be used in conjunction with an
 * {@link EdmEntityType} annotation on a class.
 * </p>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface EdmEntitySet {

    /**
     * Define the name for the EDM Entity Set. If not set a default value has to
     * be generated by the EDM provider.
     *
     * @return name for the EDM Entity Set
     */
    String name() default "";

    /**
     * Define the container name for the EDM Entity Set. If not set a default
     * value has to be generated by the EDM provider.
     *
     * @return container name for the EDM Entity Set
     */
    String container() default "";
}
