package com.bloggingit.odata.edm.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for a EDM/CSDL EntityType element.
 * <p>
 * EdmEntityType holds a set of related information like EdmPrimitiveType,
 * EdmComplexType and EdmNavigation properties.
 * </p>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface EdmEntityType {

    /**
     * Define the name for the EDM EntityType. If not set a default value has to
     * be generated by the EDM provider.
     *
     * @return name for the EDM EntityType
     */
    String name() default "";

    /**
     * Define the namespace for the EDM EntityType. If not set a default value
     * has to be generated by the EDM provider.
     *
     * @return namespace for the EDM EntityType
     */
    String namespace() default "";
}
